// ---------------------------------------------------------------------------
// Custom server.js — HTTP server + Socket.IO + Next.js (standalone-compatible)
// ---------------------------------------------------------------------------
// Replaces the default standalone server.js generated by Next.js.
// Creates a Node.js HTTP server, attaches Socket.IO for real-time events,
// and passes all HTTP requests to the Next.js request handler.
//
// In production (standalone), the build-time config is read from
// standalone-config.json and set as __NEXT_PRIVATE_STANDALONE_CONFIG so that
// require('next') skips webpack-based config loading (which isn't available in
// standalone output). In development, the normal config loading path is used.
//
// Socket.IO is initialised via the pre-compiled ESM bundle
// (socket-server.bundle.mjs), which is generated by esbuild during the
// Docker build step.
// ---------------------------------------------------------------------------

const { createServer } = require('http')
const { parse: parseUrl } = require('url')
const path = require('path')

const PORT = parseInt(process.env.PORT || '3000', 10)
const HOSTNAME = process.env.HOSTNAME || '0.0.0.0'
const dev = process.env.NODE_ENV !== 'production'

// ---------------------------------------------------------------------------
// Start server
// ---------------------------------------------------------------------------

async function startServer() {
  let requestHandler
  let upgradeHandler

  if (dev) {
    // -------------------------------------------------------------------
    // Development: use the standard next({ dev }) path
    // -------------------------------------------------------------------
    const next = require('next')
    const nextApp = next({ dev })
    requestHandler = nextApp.getRequestHandler()
    await nextApp.prepare()
  } else {
    // -------------------------------------------------------------------
    // Production (standalone): use getRequestHandlers from start-server
    // -------------------------------------------------------------------
    const configPath = path.join(__dirname, 'standalone-config.json')
    const fs = require('fs')
    let nextConfig
    try {
      nextConfig = JSON.parse(fs.readFileSync(configPath, 'utf8'))
    } catch (err) {
      console.error(
        '[server] Failed to read standalone-config.json.',
        'Did the Dockerfile extract it during build?',
        err,
      )
      process.exit(1)
    }

    // Set the env var so require('next') skips webpack-based config loading
    process.env.__NEXT_PRIVATE_STANDALONE_CONFIG = JSON.stringify(nextConfig)

    require('next')
    const { getRequestHandlers } = require('next/dist/server/lib/start-server')

    const initResult = await getRequestHandlers({
      dir: __dirname,
      port: PORT,
      hostname: HOSTNAME,
      isDev: false,
      minimalMode: false,
      keepAliveTimeout: undefined,
      experimentalHttpsServer: false,
      quiet: true,
    })

    requestHandler = initResult.requestHandler
    upgradeHandler = initResult.upgradeHandler
  }

  // -----------------------------------------------------------------------
  // Create HTTP server
  // -----------------------------------------------------------------------
  const httpServer = createServer((req, res) => {
    const parsedUrl = parseUrl(req.url, true)
    requestHandler(req, res, parsedUrl)
  })

  if (upgradeHandler) {
    httpServer.on('upgrade', (req, socket, head) => {
      upgradeHandler(req, socket, head)
    })
  }

  // -----------------------------------------------------------------------
  // Initialise Socket.IO
  // -----------------------------------------------------------------------
  try {
    const socketServer = await import('./socket-server.bundle.mjs')
    socketServer.initSocketServer(httpServer)
    console.log('[server] Socket.IO server initialised')
  } catch (err) {
    console.warn(
      '[server] Socket.IO not available:',
      err instanceof Error ? err.message : err,
    )
  }

  // -----------------------------------------------------------------------
  // Start listening
  // -----------------------------------------------------------------------
  httpServer.listen(PORT, HOSTNAME, () => {
    console.log(
      '[server] Listening on http://' + HOSTNAME + ':' + PORT + ' as ' + (dev ? 'development' : 'production'),
    )
  })

  // -----------------------------------------------------------------------
  // Graceful shutdown
  // -----------------------------------------------------------------------
  async function shutdown(signal) {
    console.log('[server] Received ' + signal + ', shutting down...')
    try {
      const socketServer = await import('./socket-server.bundle.mjs')
      await socketServer.shutdownSocketServer()
    } catch {
      // Socket server may not be initialised
    }
    httpServer.close(function () {
      console.log('[server] HTTP server closed')
      process.exit(0)
    })
    // Force exit after 10 seconds
    setTimeout(function () { process.exit(1) }, 10000)
  }

  process.on('SIGTERM', function () { shutdown('SIGTERM') })
  process.on('SIGINT', function () { shutdown('SIGINT') })
}

startServer().catch(function (err) {
  console.error('[server] Failed to start:', err)
  process.exit(1)
})
